name: MinGW Winlibs
description: Update MinGW to use winlibs which is modern GCC

runs:
  using: composite
  steps:
    - id: update
      run: |
        Invoke-WebRequest https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0posix-17.0.6-11.0.1-ucrt-r5/winlibs-x86_64-posix-seh-gcc-13.2.0-mingw-w64ucrt-11.0.1-r5.zip -OutFile C:\mingw64.zip
        Expand-Archive -Force C:\mingw64.zip -DestinationPath C:\
      shell: pwsh

branding:
  icon: star
  color: purple
